# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
