# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
