# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-05-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210511_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correcta',
            field=models.IntegerField(default=0),
        ),
    ]
